spring: 
  application:
    name: sohu.mq-cloud.online
  freemarker: 
    cache: true
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/mq-cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mqcloud
    password: mqcloud
    tomcat: 
      initial-size: 5
      min-idle: 5
      max-idle: 30
      max-active: 30